### ISSUE TITLE
Quick Code Review

### ISSUE THREAD

**Issue by RoninSTi** [abbasio/random-gif-generator#1]
Hey!  It's roninsti from reddit.  Just thought I'd leave some quick feedback for you.

Overall the site works which is great. Some general feedback:

- The first thing I went to do after typing in my keyword is push enter, and nothing happened.  One of the things I look for when evaluating developers is: Did the developer take the time to understand how someone was going to use their site.  If the first thing I did was type a phrase and hit enter, you can bet lots of other people will to!  Wrap your input in a form and use an input type of "submit" for your button and you'll get the enter key functionality.  You'll have to fire your randomGif method on form submit as opposed to the button click.  
- You set the container content in the js, perfectly fine, but if that text is never going to change, have it in the HTML instead
- Wrap your async/await logic in a try/catch so you can catch errors and present an error state if an error is generated.
- While I understand this project is simple, and I would have done the same thing you did, know how to answer the question of how you would remove your API key as a hardcoded value in your request.  On a code challenge, I'd expect people to implement how you did, but I'd expect them to know that answer.

For next steps, maybe implement this in React?  React is way overkill, but it will teach you how react works well.  Especially if you really break everything up.

Happy coding!

**Comment by abbasio** [comment]
Thanks for writing this up, I really appreciate you taking the time to do so!

- I definitely see what you're saying about the 'press enter' functionality, and it's something I agree is important to keep in mind. These kinds of changes generally aren't too difficult to do, but they can also be easy to overlook if one isn't paying attention. I'll try to be more concious about that with the stuff I develop.
- Yeah I'm honestly not sure why I wrote it like that. No clue what I was thinking.
- Error handling is definitely a weak point of mine - I'm new to developing and it's easy for me to get swept up in the excitement of making a new thing. I focus on getting the functionality working and kind of disregard accounting for errors - will make more of a concious effort to fix that going forward. Need to practice that a lot more.
- That's a really good point that I hadn't even considered. Security is generally a blind spot for me as well, and I hadn't considered the downsides of having the API key just hardcoded in the file. I don't actually know a way to remove it, but I'm pretty confident I can figure it out and will make sure to implement that.

React seems like a good next step, since it's something I want to learn regardless. This project could be a great base to learn that with. Thanks for the idea! First I'm going to work on the improvements you suggested (Press enter functionality, try/catch error handling, and hiding the API key). Then I'll see about learning React and incorporating that as well.

Really appreciate you taking the time to look at this and give thoughtful feedback. Thank you very much!
